# https://github.com/devcontainers/images/tree/main/src/python
# https://github.com/devcontainers/images/tree/main/src/python/history
FROM mcr.microsoft.com/devcontainers/python:0.203.9-3.10-bullseye

RUN pipx install pre-commit
